dashboard/lib/dashboard_web/router.ex
defmodule DashboardWeb.Router do
  use DashboardWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DashboardWeb.Plugs.Authenticate
  end

  pipeline :api do
    plug :accepts, ["html"]
  end

  scope "/", DashboardWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/painting", PageController, only: [:new, :create]
    delete "/remove/:id", PageController, :delete

    resources "/session", SessionController, only: [:new, :create]
    delete "/signout", SessionController, :delete

    resources "/register", RegisterController, only: [:new, :create]
  end

  scope "/api", DashboardWeb do
    pipe_through :api

    resources "/predict", PredictorController, only: [:create]
    post "/train", PredictorController, :train
    post "/reload", PredictorController, :reload
    get "/list-museum/:id", PredictorController, :list_museum
  end

  # Other scopes may use custom stacks.
  # scope "/api", DashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  import Phoenix.LiveDashboard.Router

  scope "/" do
    pipe_through :browser
    live_dashboard "/dashboard", metrics: DashboardWeb.Telemetry
  end
end

dashboard/lib/dashboard_web/controllers/register_controller.ex
defmodule DashboardWeb.RegisterController do
  use DashboardWeb, :controller

  plug DashboardWeb.Plugs.EnsureUnauthenticated

  def new(conn, _params) do
    render(conn, "new.html", changeset: conn)
  end

  def create(conn, %{"register" => register_params}) do
    case Dashboard.Auth.register(register_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed up!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

dashboard/lib/dashboard_web/views/register_view.ex
defmodule DashboardWeb.RegisterView do
  use DashboardWeb, :view
end

dashboard/lib/dashboard_web/templates/register/new.html.eex
<div class="auth-form-wrapper">
  <%= form_for @changeset, Routes.register_path(@conn, :create), [as: :register, class: "form-signin"], fn f -> %>
    <div class="text-center mb-4">
      <h1 class="h3 mb-3 font-weight-normal">Sign Up</h1>
    </div>

    <div class="form-label-group">
      <%= text_input f, :username, class: "form-control", placeholder: "Username", required: true, autofocus: true %>
      <%= label f, :username, "Username", class: "control-label" %>
      <%= error_tag f, :username %>
    </div>

    <div class="form-label-group">
      <%= password_input f, :password, class: "form-control", placeholder: "Password", required: true %>
      <%= label f, :password, class: "control-label" %>
      <%= error_tag f, :password %>
    </div>

    <div class="form-label-group">
      <%= password_input f, :password_confirmation, class: "form-control", placeholder: "Password confirmation", required: true %>
      <%= label f, :password_confirmation, "Password confirmation", class: "control-label" %>
      <%= error_tag f, :password_confirmation %>
    </div>

    <%= submit "Sign Up", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
</div>